### PR TITLE
Fix all deprecated functions in GTK3 <= 3.22

### PR DESCRIPTION
**Pull request by besser82**
Fixes for GTK3-3.22 are on my next batch.  This is ready to go now.

### CODE REVIEW

**Comment by besser82** [comment]
So far virtually any deprecated function, except for gtk_widget_override_*(), should be fixed now…  If anyone wants to start a review…  @mvidner @tgoettlicher @jreidinger

**Comment by besser82** [comment]
This PR is ready for review && merge now. ^_^

**Comment by anaselli** [comment]
Is this still open?

**Comment by jreidinger** [comment]
well, it was approved, but not merged and now it conflict in changes, so it need rebase on top of current master and merge it.

**Comment by hellcp** [comment]
@besser82 could I ask you to fix up conflicts? I would like to fix some parts of libyui-gtk and this is a useful PR to not to have to worry about already fixed deprecated warnings.

**Comment by Conan-Kudo** [comment]
@besser82 ping? Could you please rebase this change?

**Comment by anaselli** [comment]
Conflicts are here because of the missed merge. I think you can get the master for all of those files that are not part of the fixing. If you want to trace the changes the real difference is into **package/libyui-gtk.changes**:

- Fix Werror=misleading-indentation
- Fix all deprecated / obsoleted functions in GTK-3.12 (gh#libyui/libyui-gtk#42)
  - Remove obsolete gtk_container_set_resize_mode()
  - Replace gtk_widget_get_root_window()
- Fix all deprecated / obsoleted functions in GTK-3.14 (gh#libyui/libyui-gtk#42)
  - Remove gtk_tree_view_set_rules_hint()
  - Remove gtk_window_set_has_resize_grip()
  - Replace gtk_alignment_new()
  - Replace gtk_alignment_set_padding()
  - Replace gtk_arrow_new()
  - Replace gtk_misc_set_alignment()
  - Replace gtk_misc_set_padding()
- Fix all deprecated / obsoleted functions in GDK-3.16 (gh#libyui/libyui-gtk#42)
  - Replace gdk_cursor_new()
- Fix all deprecated / obsoleted functions in GTK-3.16 (gh#libyui/libyui-gtk#42)
  - Replace gtk_style_context_get_background_color()
- Fix all deprecated / obsoleted functions in GDK-3.20 (gh#libyui/libyui-gtk#42)
  - Replace gdk_device_manager_get_client_pointer()
- Fix all deprecated / obsoleted functions in GTK-3.20 (gh#libyui/libyui-gtk#42)
  - Replace gtk_button_set_focus_on_click()
- Fix all deprecated / obsoleted functions in GDK-3.22 (gh#libyui/libyui-gtk#42)
  - Replace gdk_screen_get_height()
  - Replace gdk_screen_get_monitor_at_window()
  - Replace gdk_screen_get_monitor_geometry()
  - Replace gdk_screen_get_width()
  - Replace gdk_visual_get_best_depth()
- Fix all deprecated / obsoleted functions in GTK-3.22 (gh#libyui/libyui-gtk#42)
  - Replace gtk_menu_popup()
  - Replace gdk_display_get_device_manager()

**Comment by besser82** [comment]
@anaselli @Conan-Kudo I'll get back to this during beginning of the week.

I think a lot of preprocessor conditionals can be removed now, as GTK v3.22 is the final release and was included in almost all recent enterprise Linux releases.

**Comment by anaselli** [comment]
@besser82 great!

**Pull request merged**
